name: timetable_projct
description: "A new Flutter project."
publish_to: "none"
version: 2.0.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  image: assets/app.png
  color: "#ffffff"
  ios: true
  android: true

  android_12:
    image: assets/app.png
    icon_background_color: "#000000"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app.png"
